### ISSUE TITLE
white tabs

### ISSUE THREAD

**Issue by BeanDx** [Haruzona/penguinFox#4]
I installed your firefox css, but the tabs, or rather the entire top bar, are white, although I chose a dark theme in the settings.

**Comment by p3nguin-kun** [comment]
screenshot or video pls

**Comment by Packjackisback** [comment]
Yep, same

**Comment by Packjackisback** [comment]
![240402_08-00-01](https://github.com/Haruzona/penguinFox/assets/83289186/582e6d7e-6d74-4066-a08d-7dfeda9bc09c)
Here is a screenshot.

**Comment by p3nguin-kun** [comment]
> ![240402_08-00-01](https://private-user-images.githubusercontent.com/83289186/318789894-582e6d7e-6d74-4066-a08d-7dfeda9bc09c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMTkzMTAsIm5iZiI6MTcxMjMxOTAxMCwicGF0aCI6Ii84MzI4OTE4Ni8zMTg3ODk4OTQtNTgyZTZkN2UtNmQ3NC00MDY2LWEwOGQtN2RmZWRhOWJjMDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDEyMTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YmI1N2M2MGQ3Yzc5MWJhZmMwM2E4Njk5YjUwZWQ1ODFlYTU0OWM5MjFmNzU1ZjY4YzI0YWQxMTViZjVkMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mahSk8VwNiKBfUMao3tgxt1M-4MLRfhF8zgtIZrux-A) Here is a screenshot.

check your gtk theme
