### ISSUE TITLE
penguinfox isn't installed to firefox flatpak on fedora silverblue

### ISSUE THREAD

**Issue by orcbolg3612** [Haruzona/penguinFox#8]
I tried ./penguinfox-installer.sh, sudo ./penguinfox-installer.sh, give root access and write on mozilla path to /home/keyhost505/.var/app/org.mozilla.firefox/cache/mozilla/firefox/h6diuxo9.default-release and /var/home/keyhost505/.var/app/org.mozilla.firefox/cache/mozilla/firefox/h6diuxo9.default-release
Nothing works. Maybe that i am using immutable os... I dunno anymore. The reason that i am not install firefox from rpm-ostree is it's doesn't have codec supported.

**Comment by orcbolg3612** [comment]
done, i tried this and it's work: https://www.reddit.com/r/degoogle/comments/168oul7/guide_how_to_get_arkenfox_working_with_firefox/?rdt=61472

**Comment by p3nguin-kun** [comment]
```/home/keyhost505/.var/app/org.mozilla.firefox/.mozilla/firefox/h6diuxo9.default-release```
